import {
  aaveConfig,
  arweaveConfig,
  connextConfig,
  defiLlamaConfig,
  dicoConfig,
  erc1155Config,
  erc20Config,
  erc721Config,
  etherscanConfig,
  gelatoConfig,
  gitcoinPassportConfig,
  lensProtocolConfig,
  litProtocolConfig,
  livepeerConfig,
  moralisConfig,
  openaiConfig,
  poolTogetherV4Config,
  pushProtocolConfig,
  sessionKeysConfig,
  starterConfig,
} from '../template/integrations'
import type { Integrations } from '../types'

export const integrationOptions: Integrations = {
  erc20: erc20Config,
  erc721: erc721Config,
  erc1155: erc1155Config,
  disco: dicoConfig,
  etherscan: etherscanConfig,
  'lit-protocol': litProtocolConfig,
  openai: openaiConfig,
  'pooltogether-v4': poolTogetherV4Config,
  'session-keys': sessionKeysConfig,
  connext: connextConfig,
  livepeer: livepeerConfig,
  gelato: gelatoConfig,
  'push-protocol': pushProtocolConfig,
  moralis: moralisConfig,
  aave: aaveConfig,
  arweave: arweaveConfig,
  'gitcoin-passport': gitcoinPassportConfig,
  'lens-protocol': lensProtocolConfig,
  starter: starterConfig,
  'defi-llama': defiLlamaConfig,
}
